### PR TITLE
Expose -fauto-combine-image-sampler compile option

### PR DESCRIPTION
**Pull request by dneto0**
Fixes up and supercedes #1181 
Thanks @Rob2309 for doing most of the work for this.

### CODE REVIEW

**Comment by dneto0** [comment]
Hey @Rob2309 please give explicit consent to land this.

**Comment by dneto0** [comment]
I had to rebase this to update the underlying  license checker.

**Comment by Rob2309** [comment]
@googlebot I consent.

**Comment by dneto0** [comment]
The VS2015 build failed with a linker crash. That happens sometimes.  I'll try to trigger it again.

**Pull request merged**
