### PR TITLE
OGLCompiler and HLSL have been removed from glslang

### PR DESCRIPTION
**Pull request by juan-lunarg**
This fixes SPIRV-Tools CI-shaderc-smoketest build failure.

### CODE REVIEW

**Comment by juan-lunarg** [comment]
See https://github.com/KhronosGroup/glslang/pull/3426 for details.

This PR should also address this shaderc smoke test build failure:
https://source.cloud.google.com/results/invocations/788aa1a5-6dc1-433c-b07d-289e3b20e2b3/targets

**Comment by dneto0** [comment]
Hm. This might fail because DEPS needs to be updated too.

**Comment by juan-lunarg** [comment]
> Hm. This might fail because DEPS needs to be updated too.

Updated DEPS.

**Comment by dneto0** [comment]
Closed in favour of #1384
Also needed an update to the docker script that tests the android build.  The glslang-standalone target is not defined for Android (or iOS) anymore.

But thank you for getting this rolling!

**Pull request closed without merging**
