### PR TITLE
Clarify Shaderc wraps around other tools

### PR DESCRIPTION
**Pull request by dneto0**
Describe why it exists: what does Shaderc add on top?

### CODE REVIEW

**Comment by dneto0** [comment]
Looking for feedback from @johnkslang: Does this clarification help?  Am I missing anything else significant?

**Comment by johnkslang** [comment]
Looks good.  

Somehow, glslang should have native #include functionality.  I can see some aspect of it might depend on environment.  When file-base processing is done offline, it makes sense to use #include functionality that is file-system based, and that's true of both glslang and Shaderc, so seems more a current accident of functionality levels than of a true reason to distinguish between the tools.  Is there a way of further characterizing what should be distinct about the #include functionality present in Shaderc?

**Comment by antiagainst** [comment]
I feel like the newly added paragraph is kinda overlap with what is already in the `File Organization` Section. But I see they emphasize different things. So I'm OK.

**Comment by antiagainst** [comment]
As a side comment, it may be handy for developers if we create tags for each NDK shipment.

**Comment by dneto0** [comment]
@johnkslang:  I agree that having some of the file-based part of #include functionality in a separate library is partly an accident.  However it did meet our goal of trying to minimize the amount of code that went into glslang itself, since *all* clients would pay the code-size cost.  It's fair to argue the dividing line was chosen poorly, and perhaps should have just talked with you about it before implementing.  Other factors were: we were far more tentative at the time, there was no gtest-based facility yet in Glslang at the time, and we felt strongly about the need for fine-grain testing of the feature, but without blocking its rollout.

@antiagainst: About the tags.  Any tags in Shaderc are not automatically carried over into the AOSP repos that the NDK builds use.  So it would be a manual process to go back and tag *this* repository with what ended up in the NDK.   In any case, the NDK release always have git commit signatures for their own contents, in "repo.prop" files.  Those signatures reference the commits in the AOSP repos.  I prefer to let that automatic mechanism be the one and only place where that info is recorded, and avoid inserting a manual and hence error-prone step here.
Maybe the right thing to do is to point to the repos at https://android.googlesource.com/platform/external/shaderc/ for the authoritative content of what's actually in the NDK. 
This would also accommodate the potential case where a patch is applied to the NDK copy of the code but which hasn't been pushed back into GitHub.  (I hope to never do that, but ....)

**Comment by dneto0** [comment]
I've added a commit to point to where NDK takes its sources from, and to say that that's downstream from GitHub

**Comment by johnkslang** [comment]
@dneto0 Perfectly understandable how we got here! I only want the #include thing rationalized rather than being a defining characteristic of the differences between shaderc and glslang.

**Comment by dneto0** [comment]
In https://github.com/google/shaderc/pull/256/commits/d5411d8443ece0c24f5bd1f6280929c175711413 I've added a parenthetical remark about how `#include` support might fully move into Glslang.
I see how the previous wording could be understood that support for `#include` is a *defining* characteristic of Shaderc.  It's just an example of where functionality materially differs today.   (My basic point was that we need to tell people it's there.  Even better would be to finally publish the extension doc.)

Note that full file-based `#include` support is also closely tied to dependency-dumping features of glslc, i.e. the -M family of options.

**Comment by johnkslang** [comment]
Yes, I think #include is complex in that it has environment-specific behavior, and hence will have support in multiple forms.  Thanks for clarifying.

**Comment by dneto0** [comment]
Rebased and squashed.

**Pull request merged**
