### PR TITLE
Add shared library variant for libshaderc

### PR DESCRIPTION
**Pull request by Kangz**
PR for a CQ dry-run. Heavily based off #342

### CODE REVIEW

**Comment by Kangz** [comment]
@AWoloszyn PTAL!

**Comment by AWoloszyn** [comment]
Hey! Sorry about the delay, somehow my GitHub emails are getting mis-classified as junk.

**Comment by AWoloszyn** [comment]
Again, sorry about the delay.
My one request is, can you add a test executable similar to shaderc_combined_test, which we can run to validate that the shared library was built and links correctly.

**Comment by Kangz** [comment]
Added the tests and ran them locally. My understanding is that they will run automatically on Travis via CTest correct?

**Comment by Kangz** [comment]
Thanks for the review! Testing passed, @antiagainst or @AWoloszyn can one of you merge this?

**Comment by AWoloszyn** [comment]
Done!

**Pull request merged**
