### PR TITLE
[kokoro] Compile for x86_64 and print CMake version on Windows

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by dneto0** [comment]
Please rebase

**Comment by antiagainst** [comment]
Done rebasing

**Comment by antiagainst** [comment]
Wait, this is causing buildbot unable to find `cl.exe`.

**Comment by antiagainst** [comment]
Er... Found yet another issue with buildbot.

Windows tests are supposed to fail but they reported as success.

**Comment by antiagainst** [comment]
The current master branch also has this problem. I'll merge this one and fix it with another PR.

**Pull request merged**
