### PR TITLE
Roll glslang dependency

### PR DESCRIPTION
**Pull request by dgkoch**
Roll third_party/glslang/ 1f0fcbe5a..8e26c5f50 (26 commits)

$ git log 1f0fcbe5a..8e26c5f50 --date=short --no-merges --format='%ad %ae %s'
2020-03-25 neslisah.torosdagli@amd.com switch format update
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com spirv.hpp reverted to commit f368dcbb7d8af23f0cba3015d0f4dda9dc3aa66d
2020-03-24 neslisah.torosdagli@amd.com .travis updated to origin, rayQueryCheck removed
2020-03-23 neslisah.torosdagli@amd.com const rayFlag defs used in the test cases in stead of numerical values
2020-03-23 neslisah.torosdagli@amd.com compute and fragment shader test_cases added for rayQuery
2020-03-23 neslisah.torosdagli@amd.com rayQuery test cases added
2020-03-23 neslisah.torosdagli@amd.com rayQueryEXT function parameter
2020-03-23 neslisah.torosdagli@amd.com rayQueryEXT assignment is allowed.
2020-03-23 neslisah.torosdagli@amd.com test names updated
2020-03-23 kainino@chromium.org update README
2020-03-23 kainino@chromium.org Fix build on CMake 2.8, and fix Web build
2020-03-23 neslisah.torosdagli@amd.com wait time increased for the install
2020-03-23 neslisah.torosdagli@amd.com rayQuery test cases disabled
2020-03-20 neslisah.torosdagli@amd.com GL_EXT_ray_query glslang updates, and test cases added.
2020-03-19 neslisah.torosdagli@amd.com comment update, rayQueryEXT is writable, readonly check removed.
2020-03-19 ntorosda@amd.com GL_EXT_ray_query updates
2020-03-18 cepheus@frii.com Fix #2132: constant matrix constructor from single non-scalar argument
2020-03-19 neslisah.torosdagli@amd.com comment update, rayQueryEXT is writable, readonly check removed.
2020-03-19 ntorosda@amd.com GL_EXT_ray_query updates
2020-03-18 cepheus@frii.com Fix #2132: constant matrix constructor from single non-scalar argument
2020-03-19 neslisah.torosdagli@amd.com comment update, rayQueryEXT is writable, readonly check removed.
2020-03-19 neslisah.torosdagli@amd.com GL_EXT_ray_query updates
2020-03-19 ntorosda@amd.com GL_EXT_ray_query updates

### CODE REVIEW

**Comment by dgkoch** [comment]
cc @zoddicus @dneto0 

This picks up ray query support in glslang.

**Comment by dgkoch** [comment]
Is there also a known_good file?  (I'm trying to figure out if I also need to do something like #1006)

**Comment by zoddicus** [comment]
I believe that is just for the NDK. dneto0@ ?

**Comment by dgkoch** [comment]
> I believe that is just for the NDK. dneto0@ ?

I want to make sure the Khronos SDK update picks it up.

**Comment by dgkoch** [comment]
CI has passed.

**Comment by zoddicus** [comment]
@dneto0, can you comment if there is anything else that needs to be done?

**Comment by dgkoch** [comment]
I think this is necessary, but it may not be sufficient. might as well get it in?
I think the known_good stuff needs to go in a separate branch, and probably has some testing procedure that is not accessible to me.

**Comment by dgkoch** [comment]
Thanks!

**Pull request merged**
