### PR TITLE
cmake: Remove redundant -std=c++11 flag

### PR DESCRIPTION
**Pull request by dneto0**
This is already covered by the CMAKE_CXX_STANDARD directive

### CODE REVIEW

**Comment by TheLavaBlock** [comment]
Hello, what is the status of this PR ?

I encountered the error when glslang started using C++17 features:  https://github.com/KhronosGroup/glslang/issues/3326

Can we merge this soon ?

**Comment by TheLavaBlock** [comment]
Hi @ben-clayton - any ETA for this?

**Comment by dneto0** [comment]
The MinGW build was removed.

**Comment by TheLavaBlock** [comment]
Thank you @dneto0 !

**Pull request merged**
