### PR TITLE
Add default ctor and move assignment to CompilationResult

### PR DESCRIPTION
**Pull request by nicebyte**

### CODE REVIEW

**Comment by nicebyte** [comment]
I'm not sure how this thing checks for CLA compliance, but please rest assured that I have, in fact, signed the CLA, am a member of this org, and no other people have participated in the PR. How can I address the failing check?

**Comment by nicebyte** [comment]
Also, I'm not quite sure what's wrong with the MSVS build - the failure seems unrelated.

**Comment by dneto0** [comment]
The error was something about PDB API failed.  That seems spurious.  I've kicked off another build. 

I've contacted @nicebyte via Twitter DM with instructions on how to register your GitHub account as a Googler for the purposes of the Google CLA.

**Comment by dneto0** [comment]
Technical question:  Why do you want the extra functionality?  Is there a problem you're fixing?

**Comment by nicebyte** [comment]
Thanks David, I replied to your DM.
As to why I need this patch: I would like to store a few CompilationResults in an STL container.

**Pull request merged**
