### PR TITLE
DRY setup_build.cmake's use of find_host_program.

### PR DESCRIPTION
**Pull request by dmircevski**

### CODE REVIEW

**Comment by dmircevski** [comment]
Hm, the modified find_program invocation isn't working quite right, so continuous builds failed.  Please hold off on reviewing this until I figure it out...

**Comment by dneto0** [comment]
I suspect beta reduction doesn't work in CMake.  ;-P
And there's a tension between DRY and simplicity here.

**Comment by dmircevski** [comment]
Nah, variable substitution works fine.  Now ready for review.  Hopefully this is still simple enough to grok.

**Comment by dneto0** [comment]
+2

**Comment by dneto0** [comment]
Merged

**Comment by dneto0** [comment]
Merged after squashing.

**Pull request closed without merging**
