### PR TITLE
Add comment to explain how to return an error in callback

### PR DESCRIPTION
**Pull request by realitix**
It's a small addition but very useful!

### CODE REVIEW

**Comment by realitix** [comment]
I signed it!

**Comment by dneto0** [comment]
Yes, you're right.  We missed documenting that in this interface.

This interface eventually tunnels down into Glslang, and we document the "empty string means error" convention there:
https://github.com/KhronosGroup/glslang/blob/master/glslang/Public/ShaderLang.h#L335
But that doesn't help you here.  :-(

This code looks good.  I plan to add a note at the source_name data member to describe the convention.

**Comment by dneto0** [comment]
Rebased and pushed into master as  48b5f885b

**Comment by dneto0** [comment]
I've pushed cb4f0f6261 to describe the error convention in the includer result struct itself.

**Comment by dneto0** [comment]
Thank you for the contribution!

**Pull request closed without merging**
