### PR TITLE
Add missing APIs for HLSL support in Dawn - set_decoration

### PR DESCRIPTION
**Pull request by sarahM0**
fixs #919

### CODE REVIEW

**Comment by sarahM0** [comment]
I'm passing the parameters as uint32_t then casting them into what they should be (static_cast<spirv_cross::ID>(id) and static_cast<spv::Decoration>(decoration)). 
1 - Dawn invokes this function and does not have access to spirv_cross namespace.
2- spvc.hpp does not have access to spv namespace.

Please let me know what you think.

**Comment by zoddicus** [comment]
I am fine with passing the ID as a uint32_t, since at its core that is all an ID is.

spv::Decorations comes from spirv.hpp in spirv-cross, which in turn is copied from spirv-headers. I think we should be using spv::Decorations in the API, instead of an uint32_t.

If spirv-cross was just using vulkan-headers as a dependency instead of copying in the data, I would just say use vulkan-headers. But because it is copying it in, so it may diverge. So we need to expose the version in spirv-cross to the use. I am not sure if we want to expose the actual spirv-cross header file or copy in the data we care about... Let me think on this for a moment.

**Comment by zoddicus** [comment]
For posterity, talked with dj2 and sarahM0 offline. A third option was proposed, having spvc version of spv::Decoration, that only had the values we support, and the internal implementation translates from that in the API to the call to spirv_cross.

**Comment by sarahM0** [comment]
Thanks for your comment @zoddicus .
Ready for review.

**Pull request merged**
