### PR TITLE
Remove use of deprecated googletest macro

### PR DESCRIPTION
**Pull request by s-perron**
INSTANTIATE_TEST_CASE_P has been deprecated. We need to use
INSTANTIATE_TEST_SUITE_P instead.

### CODE REVIEW

**Comment by fjhenigman** [comment]
A rebase will fix the ndk-build.  You're missing fcb2d4e2ff2b22147712babbb8612f5157431239

**Comment by dneto0** [comment]
To be clear, this PR or one like it will have to wait until the NDK updates its snapshot of googletest.  I don't know if that is even scheduled.

**Comment by s-perron** [comment]
There is a CL to update the NDK. It is waiting for review.

**Comment by s-perron** [comment]
The Andriod NDK has been updated.  This should be good to go.

**Pull request merged**
