### PR TITLE
Implement default builtin constants needed for GL_EXT_mesh_shader

### PR DESCRIPTION
**Pull request by pmistryNV**

### CODE REVIEW

**Comment by dgkoch** [comment]
cc @dneto0

**Comment by pmistryNV** [comment]
@dneto0 kindly merge this change.

**Comment by pmistryNV** [comment]
@alan-baker can you help merge this change?

**Comment by TheLavaBlock** [comment]
Thanks, looking forward to the fix.

**Review by dneto0 — APPROVED** [review]

**Pull request merged**
