### PR TITLE
Avoid mem leaks in counting includer test

### PR DESCRIPTION
**Pull request by dneto0**
This is caught by leak checks in Clang 3.6 address sanitizer.

This is just one of many memory leaks in our tests.  :-(

### CODE REVIEW

**Comment by dneto0** [comment]
Rebased.  Keeping the +2

**Comment by antiagainst** [comment]
Actually we can use GitHub UI to do the rebasing now. Pay attention to the merging button you'll see a triangle and then you can select "rebase and merge". Will save the pain of manually rebasing every time. :)

**Comment by dneto0** [comment]
But I'm still old-fashioned.  When I rebase I re-run the tests.  Also I can rerun an Android build for a few ABIs.  :-)

**Comment by antiagainst** [comment]
That's fair. But for small trivial changes, maybe we can leverage it.

**Pull request merged**
