### PR TITLE
The glslang-testsuite is moved into glslang.

### PR DESCRIPTION
**Pull request by dj2**
Currently ShaderC does a full copy of the glslang testsuite during the build, rewrites the test script and then runs the tests as part of ctest. The code to run those tests has been added to the GLSLang CMake script so will be added to ctest automatically.

This CL removes the glslang-testsuite from shaderc and bumps the version of glslang so we will now use the version provided directly.

### CODE REVIEW

**Comment by dj2** [comment]
Note, this requires the GLSLang side to land first.

**Comment by s-perron** [comment]
I'm not clear on how the glslang tests will be run.  Were we running them twice before?  A little more explanation on what is happening would be good.

**Comment by dj2** [comment]
Updated comment above. PTAL.

**Comment by dneto0** [comment]
Hallelujah

**Pull request merged**
