### PR TITLE
spvc: Add flags.

### PR DESCRIPTION
**Pull request by fjhenigman**
Add a bunch of command line flags to spvc.  Update tests.

### CODE REVIEW

**Comment by dneto0** [comment]
Hey @fjhenigman please rebase to resolve conflicts.

**Comment by zoddicus** [comment]
@fjhenigman are you planning on rebasing and landing this PR or should I take over it?

**Comment by fjhenigman** [comment]
> @fjhenigman are you planning on rebasing and landing this PR or should I take over it?

please take over, thanks

**Comment by zoddicus** [comment]
The online UI for conflict resolution is hanging, I am not sure if this is a transient issue or something with this patch. I am going to pull it in locally, rebase it, and re-upload it.

**Comment by zoddicus** [comment]
This is superseded by https://github.com/google/shaderc/pull/664

**Pull request closed without merging**
