### PR TITLE
Skip scanning Python files for nose tests in glslc test framework.

### PR DESCRIPTION
**Pull request by antiagainst**
Those files contain tests for the test framework; they should be
added separately.

### CODE REVIEW

**Comment by antiagainst** [comment]
This solves an import failure when `nose` is not found.

Reported in #51.

**Comment by dmircevski** [comment]
+2

**Comment by antiagainst** [comment]
@dmircevski: The previous commit has a defect. Pushed out a new commit for fixing it.

**Comment by dmircevski** [comment]
+2

**Pull request merged**
